### ISSUE TITLE
Lembra de adicionar operações de POST/PUT/DELETE.

### ISSUE THREAD

**Issue by matheusgr** [eduhique/dev-web-2020_1#1]
https://github.com/eduhique/dev-web-2020_1/blob/52946c723ffeff84eb6a7f6af4a4bf4391b2383d/backend/routes/pedido.js#L7-L12

Pode fazer alterações em cima do json carregado.

**Comment by eduhique** [comment]
Estive doente nos últimos dias, mas devo estar colocando atualizações esses dias referente a issue...

**Comment by eduhique** [comment]
@matheusgr issue resolvida com o commit [58f5f8f](https://github.com/eduhique/dev-web-2020_1/commit/58f5f8fe596e0386efcb8a0528c62c9a1010e8b8).
