### ISSUE TITLE
Endereço de entrega dos romaneios

### ISSUE THREAD

**Issue by anarcoqzn** [eduhique/dev-web-2020_1#2]
Aparentemente, não vi um atributo que armazene o endereço de entrega dos romaneios. Pode ser que seja importante para o usuário da aplicação saber pra onde enviar os produtos pedidos pelos clientes. Ele tendo essa informação no objeto de pedido, por exemplo, fica fácil direcionar os pedidos para o endereço solicitado.

**Comment by eduhique** [comment]
O objetivo da aplicação não é entregas, mas apenas gerenciamento de estoque/pedidos para compra ou venda. Ele foi criado para suprir a deficiência que existe nas mais diversas aplicações de vendas comuns, que não permite gerenciar os pedidos dessa forma. Então a aplicação foi criada para complementar outras aplicações de vendas existentes de maneira rápida e eficiente. ex: Ele tem clientes cadastrados em seu app de venda comum e precisa fazer um levantamento de pedidos para criar uma carga para compra, então a aplicação vai tanto facilitar a compra, quanto posteriormente separar os pedidos.
Em evoluções da aplicação existem outras funcionalidades que podem ser úteis que podem ser adicionadas, como a que sugeriu, mas não as coloquei, pois pretendo evoluir aos poucos sem me atrapalhar com a complexidade crescente.
