### ISSUE TITLE
Adicionar parâmetros de busca nas próprias rotas de listagem

### ISSUE THREAD

**Issue by yurikelvin** [eduhique/dev-web-2020_1#3]
Notei que a rota de cliente e de romaneio possuem um /search depois do nome ficando por exemplo cliente/search/?s=mercadinho por exemplo, uma prática comum e utilizada nas API REST é deixar essas querys na própria rota de listagem por exemplo /cliente?search=mercadinho como descrito aqui https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9 . Colocando as queries por parâmetros na própria rota faz sentido pois são filtros que podem ser aplicado a aquela listagem, fazendo sua aplicação ficar mais concisa e de fácil uso para quem vai usar.

**Comment by eduhique** [comment]
Isso aconteceu por causa de uns problemas que estava tendo que eu achei que nisso. No fim não era e acabei não mudando. Obrigado, por lembrar

**Comment by eduhique** [comment]
dicas apontadas resolvidas com o pull request #7
