### ISSUE TITLE
Routes e Controllers

### ISSUE THREAD

**Issue by camilacarvalho** [eduhique/dev-web-2020_1#5]
https://github.com/eduhique/dev-web-2020_1/blob/3eb4f670c6ef037b554d2c54f822f812eca6d75e/backend/routes/productController.js#L39-L48

Vi que em seu projeto você tem uma pasta router e nela tem arquivos chamados controllers porém você tem rotas e o controllers juntos nesse arquivo. Acredito que seria interessante criar uma pasta Controller, colocar nele apenas os controllers e deixar em routes apenas o código referente as rotas. [Esse site ](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes)dá um exemplo bem legal para essa separação de controllers e routes.

**Comment by eduhique** [comment]
Excelente observação, como o foco não necessariamente o backend não me atentei em seguir um modelo, mas apenas na lógica funcionar. vou trabalhar nessa modificação e iriei indicar conclusão por aqui.

**Comment by eduhique** [comment]
dicas apontadas resolvidas com o pull request #7
