### ISSUE TITLE
Diretórios do backend

### ISSUE THREAD

**Issue by camilacarvalho** [eduhique/dev-web-2020_1#6]
No backend tem pastas com nomes em português "dados", "objetos" e outras em inglês como "public" e "routes". Uma outra sugestão é colocar todos os diretórios das pastas do backend em inglês ou em português. Sugiro colocar tudo em inglês.

**Comment by eduhique** [comment]
ok, vou organizar

**Comment by eduhique** [comment]
dicas apontadas resolvidas com o pull request #7
